# Generated by Django 5.2.16 on 2026-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('KD1', 'Konsep Dasar 1'), ('KD2', 'Konsep Dasar 2'), ('EASY', 'Try Out Easy'), ('MEDIUM', 'Try Out Medium'), ('HARD', 'Try Out Hard')], default='KD1', max_length=10)),
                ('pertanyaan', models.TextField()),
                ('gambar_soal', models.ImageField(blank=True, null=True, upload_to='soal/')),
                ('pilihan_a', models.CharField(max_length=255)),
                ('pilihan_b', models.CharField(max_length=255)),
                ('pilihan_c', models.CharField(max_length=255)),
                ('pilihan_d', models.CharField(max_length=255)),
                ('pilihan_e', models.CharField(blank=True, max_length=255)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('pembahasan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
