# Generated by Django 6.0.7 on 2026-07-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=255)),
                ('pilihan_b', models.CharField(max_length=255)),
                ('pilihan_c', models.CharField(max_length=255)),
                ('pilihan_d', models.CharField(max_length=255)),
                ('jawaban_benar', models.CharField(max_length=1)),
            ],
        ),
    ]
