# Generated by Django 5.2.16 on 2026-07-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1)),
                ('dibuat_pada', models.DateTimeField(auto_now=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian.soal')),
            ],
        ),
    ]
