# Generated by Django 5.2.16 on 2026-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0003_jawabanpeserta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='pilihan_e',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
