# Generated by Django 5.2.16 on 2026-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0005_sesiujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='kategori',
            field=models.CharField(choices=[('KD1', 'Konsep Dasar 1'), ('KD2', 'Konsep Dasar 2'), ('EASY', 'Try Out Easy'), ('MEDIUM', 'Try Out Medium'), ('HARD', 'Try Out Hard')], default='KD1', max_length=10),
        ),
        migrations.AddField(
            model_name='soal',
            name='pembahasan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='pilihan_e',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
