# Generated by Django 5.2.16 on 2026-08-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0006_soal_kategori_soal_pembahasan_alter_soal_pilihan_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sesiujian',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('timer_menit', models.IntegerField(default=0)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtests', to='ujian.paketujian')),
            ],
        ),
        migrations.AddField(
            model_name='sesiujian',
            name='subtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesi', to='ujian.subtest'),
        ),
        migrations.AddField(
            model_name='soal',
            name='subtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soal', to='ujian.subtest'),
        ),
    ]
