# Generated by Django 5.2.16 on 2026-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0007_paketujian_alter_sesiujian_waktu_mulai_subtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='urutan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
