# Generated by Django 5.2.16 on 2026-08-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0008_soal_urutan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('KD1', 'Konsep Dasar 1'), ('KD2', 'Konsep Dasar 2'), ('EASY', 'Try Out Easy'), ('MEDIUM', 'Try Out Medium'), ('HARD', 'Try Out Hard')], max_length=10, unique=True, verbose_name='Kategori')),
                ('soal_per_subtest', models.PositiveIntegerField(default=10, help_text='Jumlah soal acak per subtest. 0 = tampilkan semua soal.')),
                ('timer_menit', models.PositiveIntegerField(default=10, help_text='Durasi waktu per subtest dalam menit. 0 = tidak ada batas waktu.')),
            ],
            options={
                'verbose_name': 'Pengaturan Kategori',
                'verbose_name_plural': 'Pengaturan Kategori',
            },
        ),
        migrations.AddField(
            model_name='subtest',
            name='soal_tampil',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah soal yang ditampilkan secara acak. 0 = tampilkan semua soal.'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='timer_menit',
            field=models.IntegerField(default=0, help_text='Durasi waktu ujian dalam menit. 0 = tidak ada batas waktu.'),
        ),
        migrations.CreateModel(
            name='SoalSesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil soal dalam sesi ini')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_sesi', to='ujian.sesiujian')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_sesi', to='ujian.soal')),
            ],
            options={
                'ordering': ['urutan'],
                'unique_together': {('sesi', 'soal')},
            },
        ),
    ]
