# Generated by Django 5.2.16 on 2026-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0009_kategorisetting_subtest_soal_tampil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_cheat_aktif', models.BooleanField(default=False, help_text='Aktifkan mode Anti-Cheat (blokir copy, klik kanan, F12, pindah tab)')),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
            },
        ),
    ]
