# Generated by Django 5.2.16 on 2026-08-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0010_sistemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpeserta',
            name='is_benar_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='kategori_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='paket_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='paket_nama_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='subtest_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpeserta',
            name='subtest_nama_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jawabanpeserta',
            name='soal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ujian.soal'),
        ),
    ]
