# Generated by Django 5.2.16 on 2026-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0011_jawabanpeserta_is_benar_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemsetting',
            name='network_online',
            field=models.BooleanField(default=False, help_text='Tentukan apakah server bisa diakses perangkat lain secara online (True) atau ditutup (False).'),
        ),
        migrations.AddField(
            model_name='sistemsetting',
            name='network_password',
            field=models.CharField(blank=True, default='admin123', help_text='Password wajib untuk perangkat luar (HP/Tablet/Laptop lain) jika mode jaringan sedang Online.', max_length=50),
        ),
    ]
