# Generated by Django 5.2.16 on 2026-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0012_sistemsetting_network_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='referensi_internal',
            field=models.CharField(blank=True, help_text='Menyimpan metadata asli seperti [HOTS Prosus/Inten]', max_length=255, null=True),
        ),
    ]
