# Generated by Django 5.2.16 on 2026-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0013_soal_referensi_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='topik_materi',
            field=models.CharField(blank=True, help_text='Kategori spesifik (misal: Premis, Konklusi) untuk pengelompokan porsi seimbang saat soal diacak secara terbatas.', max_length=100, null=True),
        ),
    ]
