# Generated by Django 5.2.16 on 2026-08-13 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0014_soal_topik_materi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPaketUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(max_length=100)),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
                ('durasi_teks', models.CharField(blank=True, max_length=50, null=True)),
                ('skor_json', models.JSONField(default=dict)),
                ('nilai_akhir', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
