# Generated by Django 5.2.16 on 2026-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0015_hasilpaketujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemsetting',
            name='public_url',
            field=models.CharField(blank=True, help_text='URL publik sementara yang dihasilkan oleh LocalTunnel (otomatis).', max_length=255, null=True),
        ),
    ]
