# Generated by Django 5.2.16 on 2026-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0016_sistemsetting_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemsetting',
            name='network_local',
            field=models.BooleanField(default=False, help_text='Tentukan apakah server bisa diakses perangkat lain secara lokal (Satu Wi-Fi).'),
        ),
        migrations.AlterField(
            model_name='sistemsetting',
            name='network_online',
            field=models.BooleanField(default=False, help_text='Tentukan apakah server bisa diakses perangkat lain secara online global (Tunnel).'),
        ),
    ]
