# Generated by Django 5.2.16 on 2026-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0017_sistemsetting_network_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiujian',
            name='terindikasi_curang',
            field=models.BooleanField(default=False),
        ),
    ]
